version: v1.0
name: deploy_package
jobs:
- job: Deploy package
  steps:
  - checkout: '{{.cds.workspace}}'
  - artifactDownload:
      path: .
      tag: '{{.cds.version}}'
  - script: |
      for ARCHIVE_FILE in $(ls *.tar.gz)
      do
        tar xf $ARCHIVE_FILE 
      done
      if [ "x{{.git.branch}}" = "xmaster" ]
      then
        echo "On master branch, signing"
        worker tmpl {{.cds.workspace}}/.cds/signing_key_template.yaml {{.cds.workspace}}/signing_key.priv
        find "{{.cds.workspace}}/source" \( -name '*.img.gz' -or -name 'Packages' \) -exec ./usign-x86_64 -S -m {} -s "signing_key.priv" \;
      fi
      tar cf "{{.cds.workspace}}/binary_produced.tar.gz" source
      SSH_KEY_FILE=.ssh/id_rsa
      worker key install env-deploy --file $SSH_KEY_FILE
      DEPLOY_USERNAME={{.cds.env.deployUsername | default "deploy"}}
      DEPLOY_PORT={{.cds.env.deployPort | default "22"}}
      DEPLOY_DESTINATION={{.git.branch | default .git.tag}}
      DEPLOY_SERVER={{.cds.env.deployServer}}
      SSH_OPTION="-i $SSH_KEY_FILE -o StrictHostKeyChecking=no -p $DEPLOY_PORT"
      OTB_PATH="ovh/{{.git.repository}}/$DEPLOY_DESTINATION"
      IFS=','
      for DEPLOY_HOST in $DEPLOY_SERVER
      do
        unset IFS
        ssh $SSH_OPTION $DEPLOY_USERNAME@$DEPLOY_HOST mkdir -p deploy/$OTB_PATH
        echo "ssh $SSH_OPTION $DEPLOY_USERNAME@$DEPLOY_HOST mkdir -p deploy/$OTB_PATH"
        rsync -av --delete-after -e "ssh $SSH_OPTION" source/bin/ $DEPLOY_USERNAME@$DEPLOY_HOST:deploy/$OTB_PATH/
      done
  - artifactUpload:
      path: '{{.cds.workspace}}/binary_produced.tar.gz'
      tag: '{{.cds.version}}'
  requirements:
  - binary: git
  - binary: rsync
