version: v1.0
name: overthebox-build
jobs:
- job: Build image feeds
  steps:
  - gitClone:
      branch: '{{.git.branch}}'
      commit: '{{.git.hash}}'
      directory: '{{.cds.workspace}}'
      privateKey: proj-stash.key
      url: '{{.git.url}}'
  - script: 
    - '#!/bin/sh'
    -  NB_PROC=$(cat /proc/cpuinfo | grep -i "^processor" | wc -l)
    -  export FORCE_UNSAFE_CONFIGURE=1
    -  '{{.cds.workspace}}/build.sh -j$NB_PROC | tee build.log'
    -  tar cvf binary.tar.gz source/bin
    -  BUILD_LOG=$(cat build.log | tail -n 200 | base64)
    -  worker export logcontent "$BUILD_LOG"
  - artifactUpload:
      path: '{{.cds.workspace}}/binary.tar.gz'
      tag: '{{.cds.version}}'
  - artifactUpload:
      path: '{{.cds.workspace}}/source/staging_dir/host/bin/usign'
      tag: '{{.cds.version}}'
  requirements:
  - model: compute.gra1/Debian10-GRA1
  - binary: git
