version: v1.0
name: sign_package
jobs:
- job: Sign package
  steps:
  - gitClone:
      branch: '{{.git.branch}}'
      commit: '{{.git.hash}}'
      directory: '{{.cds.workspace}}'
      privateKey: proj-stash.key
      url: '{{.git.url}}'
  - artifactDownload:
      path: .
      tag: '{{.cds.version}}'
  - script:
    - ls
    - worker tmpl {{.cds.workspace}}/.cds/signing_key_template.yaml {{.cds.workspace}}/signing_key.priv
    - tar xf binary.tar.gz
    - env
    - ""
    - find "{{.cds.workspace}}/source" \( -name '*.img.gz' -or -name 'Packages' \) -exec ./usign -S -m {} -s "signing_key.priv" \;
    - find "{{.cds.workspace}}/source" \( -name '*.img.gz' -or -name 'Packages' \) -exec echo {} \;
    - ""
  requirements:
  - binary: git
